### PR TITLE
[RFR] Fix Datepicker JS error

### LINKED ISSUE #961: Problem with DateField
JS error in ng-admin-demo in creation view

### PR DESCRIPTION
**Pull request by fzaninotto**
Closes #961

### CODE REVIEW

**Comment by fzaninotto** [comment]
Switching to RFR

File: src/javascripts/ng-admin/Crud/field/maDateField.js [hunk 1]
```diff
@@ -13,7 +13,7 @@ export default function maDateField() {
         link: function(scope, element) {
             var field = scope.field();
             scope.name = field.name();
-            scope.rawValue = scope.value;
+            scope.rawValue = scope.value == null ? new Date() : (scope.value instanceof Date ? scope.value : new Date(scope.value));
```
Comment (SebLours) [inline src/javascripts/ng-admin/Crud/field/maDateField.js]: A `null` value can not be displayed now with
```js
scope.value == null ? new Date()
```

Comment (fzaninotto) [inline src/javascripts/ng-admin/Crud/field/maDateField.js]: True, already reported in #988
