### PR TITLE
[RFR] Fix double call on reference fields

### LINKED ISSUE #712: Duplicated api calls for reference fields
Hi,

I have an address entity with two reference fields  
- user
- country

references

To populate reference values, the application makes 2 api calls for each reference ...

api_calls

```javascript
/**
 * Creation view
 */
address.creationView()
    .title("Ajouter une adresse client")
    .url("addresses/")
    .fields([
        nga.field("user", "reference")
            .label("Client")
            .targetEntity(appConfig.entities.user)
            .targetField(nga.field("username"))
            .perPage(10)
            .remoteComplete(true, {
                searchQuery: function(search) {
                    return {query: search};
                }
            }),
        address.editionView().fields()

    ])
;
```
How can i debug this ?

Thanks
Seb

### PR DESCRIPTION
**Pull request by fzaninotto**
- [x] fix `reference` field
- [x] fix `reference_many` field

Closes #712, supersedes #728

### CODE REVIEW

**Comment by fzaninotto** [comment]
What's left for RFR?

**Comment by jeromemacias** [comment]
Tests had been fixed (thanks @jpetitcolas for help ;))

File: src/javascripts/test/unit/Crud/field/maReferenceManyFieldSpec.js [hunk 1]
```diff
@@ -67,6 +72,8 @@ describe('ReferenceManyField', function() {
     });
 
     it('should call remote API when inputting first characters', function () {
+        scope.field.remoteComplete(true);
```
Comment (jeromemacias) [inline src/javascripts/test/unit/Crud/field/maReferenceManyFieldSpec.js]: This one was missing before our changes.
