### PR TITLE
[RFR] Fix several bugs

### LINKED ISSUE #458: Demo: "Error: Route is mandatory when creating new Restangular objects" when trying to create a new item
- download the demo project
- try to create a new item

Refs https://gitter.im/marmelab/ng-admin?at=555e55d8a8a48692266252bc

### PR DESCRIPTION
**Pull request by jeromemacias**
Fix #458, #454, #455, #458 and #459.

Bonus: fix issue when using 'ng-strict-di' mode.

### CODE REVIEW

File: src/javascripts/ng-admin/Crud/button/maExportToCsvButton.js [hunk 1]
```diff
@@ -30,9 +32,10 @@ define(function () {
                 scope.exportToCsv = function () {
 
                     ReadQueries.getAll(exportView, -1, true, $stateParams.search, $stateParams.sortField, $stateParams.sortDir).then(function (response) {
-                        var results = [], entries = response.entries;
+                        console.log(response);
```
Comment (jpetitcolas) [inline src/javascripts/ng-admin/Crud/button/maExportToCsvButton.js]: Debug spotted

File: src/javascripts/ng-admin/Crud/routing.js [hunk 2]
```diff
@@ -258,28 +258,24 @@ function routing($stateProvider) {
...
+                    var choceEntries;
 
-                    for (var name in referencedData) {
-                        referencedEntries = dataStore.mapEntries(
-                            references[name].targetEntity().name(),
-                            references[name].targetEntity().identifier(),
-                            [references[name].targetField()],
-                            referencedData[name]
+                    for (var name in filterData) {
+                        choceEntries = dataStore.mapEntries(
```
Comment (jpetitcolas) [inline src/javascripts/ng-admin/Crud/routing.js]: Typo: cho**i**ceEntries
