### PR TITLE
[RFR] Fix file field

### LINKED ISSUE #597: File field for file upload
I am using ng-admin file field for file upload. 
When I use ng-admin-master version 24/06/2015 everything is working ok. In all browsers: IE, FF, Chrome.
But when I try to use later ng-admin-master version (for example 19/07/2015 or 06/08/2015) file upload does not work. In all browsers also.
What is wrong? What can cause this problem?

### PR DESCRIPTION
**Pull request by jeromemacias**
Fix #597

### CODE REVIEW

File: src/javascripts/ng-admin/Crud/field/maFileField.js [hunk 1]
```diff
@@ -52,6 +52,7 @@ define(function (require) {
                     }
 
                     scope.fileSelected = function(selectedFiles) {
+                        console.log(selectedFiles);
```
Comment (fzaninotto) [inline src/javascripts/ng-admin/Crud/field/maFileField.js]: debug spotted

**Comment by jeromemacias** [comment]
@fzaninotto Tests are ok, fail is due to data that had been changed on the public demo...
